# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(choices=[('Araceae', 'Araceae'), ('Begonia', 'Begonia'), ('Cactus', 'Cactus'), ('Dacrymycetes', 'Dacrymycetes'), ('Nymphaeaceae', 'Nymphaeaceae'), ('Rutaceae', 'Rutaceae')], default='Araceae', max_length=100)),
                ('description', models.TextField(max_length=600)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('light_intensity', models.IntegerField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
